name: ci-cd pipeline
on: [push]
env:
  IMAGE_NAME: guckguck/gitlab-example
  # // image tag to 2.0.0
  IMAGE_TAG: 2.0.0
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -Ur src/requirements.txt
      - name: run tests
        run: pytest -v src
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}